name: memory_match_game
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  amplify_api: ^2.3.0
  amplify_auth_cognito: ^2.3.0
  amplify_authenticator: ^2.1.1
  amplify_flutter: ^2.3.0
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  go_router: ^14.2.3
  flutter_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0

dev_dependencies:
  amplify_lints: ^3.0.0
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  riverpod_generator: ^2.1.3
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
